import Vue from 'vue'
import { Icon, Row, Col, Input, Form, FormItem, Button, Checkbox, Message, MessageBox, Radio, Tabs, TabPane, Popover,
  Popconfirm, Table, TableColumn, Dialog, Card, Pagination, Select, Option, RadioGroup, CheckboxGroup, Dropdown, DropdownItem, 
  DropdownMenu, Container, Header, Main, Divider,Menu,MenuItem, Footer, Aside, Tag, Loading,Submenu,MenuItemGroup,Drawer} from 'element-ui'
Vue.use(Icon)
Vue.use(Row)
Vue.use(Col)
Vue.use(Input)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Button)
Vue.use(Checkbox)
Vue.use(Radio)
Vue.use(Tabs)
Vue.use(TabPane)
Vue.use(Popover)
Vue.use(Popconfirm)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Dialog)
Vue.use(Card)
Vue.use(Pagination)
Vue.use(Select)
Vue.use(Option)
Vue.use(RadioGroup)
Vue.use(CheckboxGroup)
Vue.use(Dropdown)
Vue.use(DropdownItem)
Vue.use(DropdownMenu)
Vue.use(Container)
Vue.use(Header)
Vue.use(Main)
Vue.use(Divider)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(Footer)
Vue.use(Aside)
Vue.use(Tag)
Vue.use(Loading.directive)
Vue.use(Submenu)
Vue.use(MenuItemGroup)
Vue.use(Drawer)
// 与别的不同 Message 需要挂载到Vue的原型对象上
Vue.prototype.$message = Message
Vue.prototype.$confirm = MessageBox.confirm
